// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: staking.proto

package types

import (
	context "context"
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type ValidatorStatus int32

const (
	ValidatorStatus_VALIDATOR_STATUS_NOT_FOUND ValidatorStatus = 0
	ValidatorStatus_VALIDATOR_STATUS_ACTIVE    ValidatorStatus = 1
	ValidatorStatus_VALIDATOR_STATUS_PENDING   ValidatorStatus = 2
	ValidatorStatus_VALIDATOR_STATUS_JAIL      ValidatorStatus = 3
)

var ValidatorStatus_name = map[int32]string{
	0: "VALIDATOR_STATUS_NOT_FOUND",
	1: "VALIDATOR_STATUS_ACTIVE",
	2: "VALIDATOR_STATUS_PENDING",
	3: "VALIDATOR_STATUS_JAIL",
}

var ValidatorStatus_value = map[string]int32{
	"VALIDATOR_STATUS_NOT_FOUND": 0,
	"VALIDATOR_STATUS_ACTIVE":    1,
	"VALIDATOR_STATUS_PENDING":   2,
	"VALIDATOR_STATUS_JAIL":      3,
}

func (x ValidatorStatus) String() string {
	return proto.EnumName(ValidatorStatus_name, int32(x))
}

func (ValidatorStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_289e7c8aea278311, []int{0}
}

type ChainNativeCurrency struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Symbol               string   `protobuf:"bytes,2,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Decimals             uint32   `protobuf:"varint,3,opt,name=decimals,proto3" json:"decimals,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChainNativeCurrency) Reset()         { *m = ChainNativeCurrency{} }
func (m *ChainNativeCurrency) String() string { return proto.CompactTextString(m) }
func (*ChainNativeCurrency) ProtoMessage()    {}
func (*ChainNativeCurrency) Descriptor() ([]byte, []int) {
	return fileDescriptor_289e7c8aea278311, []int{0}
}
func (m *ChainNativeCurrency) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChainNativeCurrency.Unmarshal(m, b)
}
func (m *ChainNativeCurrency) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChainNativeCurrency.Marshal(b, m, deterministic)
}
func (m *ChainNativeCurrency) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChainNativeCurrency.Merge(m, src)
}
func (m *ChainNativeCurrency) XXX_Size() int {
	return xxx_messageInfo_ChainNativeCurrency.Size(m)
}
func (m *ChainNativeCurrency) XXX_DiscardUnknown() {
	xxx_messageInfo_ChainNativeCurrency.DiscardUnknown(m)
}

var xxx_messageInfo_ChainNativeCurrency proto.InternalMessageInfo

func (m *ChainNativeCurrency) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ChainNativeCurrency) GetSymbol() string {
	if m != nil {
		return m.Symbol
	}
	return ""
}

func (m *ChainNativeCurrency) GetDecimals() uint32 {
	if m != nil {
		return m.Decimals
	}
	return 0
}

type ChainExplorer struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Url                  string   `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	Standard             string   `protobuf:"bytes,3,opt,name=standard,proto3" json:"standard,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChainExplorer) Reset()         { *m = ChainExplorer{} }
func (m *ChainExplorer) String() string { return proto.CompactTextString(m) }
func (*ChainExplorer) ProtoMessage()    {}
func (*ChainExplorer) Descriptor() ([]byte, []int) {
	return fileDescriptor_289e7c8aea278311, []int{1}
}
func (m *ChainExplorer) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChainExplorer.Unmarshal(m, b)
}
func (m *ChainExplorer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChainExplorer.Marshal(b, m, deterministic)
}
func (m *ChainExplorer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChainExplorer.Merge(m, src)
}
func (m *ChainExplorer) XXX_Size() int {
	return xxx_messageInfo_ChainExplorer.Size(m)
}
func (m *ChainExplorer) XXX_DiscardUnknown() {
	xxx_messageInfo_ChainExplorer.DiscardUnknown(m)
}

var xxx_messageInfo_ChainExplorer proto.InternalMessageInfo

func (m *ChainExplorer) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ChainExplorer) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *ChainExplorer) GetStandard() string {
	if m != nil {
		return m.Standard
	}
	return ""
}

type Chain struct {
	ChainId              uint64               `protobuf:"varint,1,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	ProjectUrl           string               `protobuf:"bytes,2,opt,name=project_url,json=projectUrl,proto3" json:"project_url,omitempty"`
	Name                 string               `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	ShortName            string               `protobuf:"bytes,4,opt,name=short_name,json=shortName,proto3" json:"short_name,omitempty"`
	Rpc                  []string             `protobuf:"bytes,5,rep,name=rpc,proto3" json:"rpc,omitempty"`
	Faucet               []string             `protobuf:"bytes,6,rep,name=faucet,proto3" json:"faucet,omitempty"`
	NativeCurrency       *ChainNativeCurrency `protobuf:"bytes,7,opt,name=native_currency,json=nativeCurrency,proto3" json:"native_currency,omitempty"`
	Explorer             []*ChainExplorer     `protobuf:"bytes,8,rep,name=explorer,proto3" json:"explorer,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Chain) Reset()         { *m = Chain{} }
func (m *Chain) String() string { return proto.CompactTextString(m) }
func (*Chain) ProtoMessage()    {}
func (*Chain) Descriptor() ([]byte, []int) {
	return fileDescriptor_289e7c8aea278311, []int{2}
}
func (m *Chain) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Chain.Unmarshal(m, b)
}
func (m *Chain) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Chain.Marshal(b, m, deterministic)
}
func (m *Chain) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Chain.Merge(m, src)
}
func (m *Chain) XXX_Size() int {
	return xxx_messageInfo_Chain.Size(m)
}
func (m *Chain) XXX_DiscardUnknown() {
	xxx_messageInfo_Chain.DiscardUnknown(m)
}

var xxx_messageInfo_Chain proto.InternalMessageInfo

func (m *Chain) GetChainId() uint64 {
	if m != nil {
		return m.ChainId
	}
	return 0
}

func (m *Chain) GetProjectUrl() string {
	if m != nil {
		return m.ProjectUrl
	}
	return ""
}

func (m *Chain) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Chain) GetShortName() string {
	if m != nil {
		return m.ShortName
	}
	return ""
}

func (m *Chain) GetRpc() []string {
	if m != nil {
		return m.Rpc
	}
	return nil
}

func (m *Chain) GetFaucet() []string {
	if m != nil {
		return m.Faucet
	}
	return nil
}

func (m *Chain) GetNativeCurrency() *ChainNativeCurrency {
	if m != nil {
		return m.NativeCurrency
	}
	return nil
}

func (m *Chain) GetExplorer() []*ChainExplorer {
	if m != nil {
		return m.Explorer
	}
	return nil
}

type Validator struct {
	Address              string          `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Owner                string          `protobuf:"bytes,2,opt,name=owner,proto3" json:"owner,omitempty"`
	Status               ValidatorStatus `protobuf:"varint,3,opt,name=status,proto3,enum=com.ankr.ValidatorStatus" json:"status,omitempty"`
	Commission           uint32          `protobuf:"varint,4,opt,name=commission,proto3" json:"commission,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *Validator) Reset()         { *m = Validator{} }
func (m *Validator) String() string { return proto.CompactTextString(m) }
func (*Validator) ProtoMessage()    {}
func (*Validator) Descriptor() ([]byte, []int) {
	return fileDescriptor_289e7c8aea278311, []int{3}
}
func (m *Validator) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Validator.Unmarshal(m, b)
}
func (m *Validator) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Validator.Marshal(b, m, deterministic)
}
func (m *Validator) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Validator.Merge(m, src)
}
func (m *Validator) XXX_Size() int {
	return xxx_messageInfo_Validator.Size(m)
}
func (m *Validator) XXX_DiscardUnknown() {
	xxx_messageInfo_Validator.DiscardUnknown(m)
}

var xxx_messageInfo_Validator proto.InternalMessageInfo

func (m *Validator) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *Validator) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *Validator) GetStatus() ValidatorStatus {
	if m != nil {
		return m.Status
	}
	return ValidatorStatus_VALIDATOR_STATUS_NOT_FOUND
}

func (m *Validator) GetCommission() uint32 {
	if m != nil {
		return m.Commission
	}
	return 0
}

type ValidatorHistory struct {
	Address              string     `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Changes              *Validator `protobuf:"bytes,2,opt,name=changes,proto3" json:"changes,omitempty"`
	TransactionHash      string     `protobuf:"bytes,3,opt,name=transaction_hash,json=transactionHash,proto3" json:"transaction_hash,omitempty"`
	BlockNumber          uint64     `protobuf:"varint,4,opt,name=block_number,json=blockNumber,proto3" json:"block_number,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *ValidatorHistory) Reset()         { *m = ValidatorHistory{} }
func (m *ValidatorHistory) String() string { return proto.CompactTextString(m) }
func (*ValidatorHistory) ProtoMessage()    {}
func (*ValidatorHistory) Descriptor() ([]byte, []int) {
	return fileDescriptor_289e7c8aea278311, []int{4}
}
func (m *ValidatorHistory) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ValidatorHistory.Unmarshal(m, b)
}
func (m *ValidatorHistory) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ValidatorHistory.Marshal(b, m, deterministic)
}
func (m *ValidatorHistory) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ValidatorHistory.Merge(m, src)
}
func (m *ValidatorHistory) XXX_Size() int {
	return xxx_messageInfo_ValidatorHistory.Size(m)
}
func (m *ValidatorHistory) XXX_DiscardUnknown() {
	xxx_messageInfo_ValidatorHistory.DiscardUnknown(m)
}

var xxx_messageInfo_ValidatorHistory proto.InternalMessageInfo

func (m *ValidatorHistory) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *ValidatorHistory) GetChanges() *Validator {
	if m != nil {
		return m.Changes
	}
	return nil
}

func (m *ValidatorHistory) GetTransactionHash() string {
	if m != nil {
		return m.TransactionHash
	}
	return ""
}

func (m *ValidatorHistory) GetBlockNumber() uint64 {
	if m != nil {
		return m.BlockNumber
	}
	return 0
}

type ValidatorDeposit struct {
	Validator            string   `protobuf:"bytes,1,opt,name=validator,proto3" json:"validator,omitempty"`
	Amount               string   `protobuf:"bytes,2,opt,name=amount,proto3" json:"amount,omitempty"`
	Epoch                uint64   `protobuf:"varint,3,opt,name=epoch,proto3" json:"epoch,omitempty"`
	TransactionHash      string   `protobuf:"bytes,4,opt,name=transaction_hash,json=transactionHash,proto3" json:"transaction_hash,omitempty"`
	BlockNumber          uint64   `protobuf:"varint,5,opt,name=block_number,json=blockNumber,proto3" json:"block_number,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ValidatorDeposit) Reset()         { *m = ValidatorDeposit{} }
func (m *ValidatorDeposit) String() string { return proto.CompactTextString(m) }
func (*ValidatorDeposit) ProtoMessage()    {}
func (*ValidatorDeposit) Descriptor() ([]byte, []int) {
	return fileDescriptor_289e7c8aea278311, []int{5}
}
func (m *ValidatorDeposit) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ValidatorDeposit.Unmarshal(m, b)
}
func (m *ValidatorDeposit) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ValidatorDeposit.Marshal(b, m, deterministic)
}
func (m *ValidatorDeposit) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ValidatorDeposit.Merge(m, src)
}
func (m *ValidatorDeposit) XXX_Size() int {
	return xxx_messageInfo_ValidatorDeposit.Size(m)
}
func (m *ValidatorDeposit) XXX_DiscardUnknown() {
	xxx_messageInfo_ValidatorDeposit.DiscardUnknown(m)
}

var xxx_messageInfo_ValidatorDeposit proto.InternalMessageInfo

func (m *ValidatorDeposit) GetValidator() string {
	if m != nil {
		return m.Validator
	}
	return ""
}

func (m *ValidatorDeposit) GetAmount() string {
	if m != nil {
		return m.Amount
	}
	return ""
}

func (m *ValidatorDeposit) GetEpoch() uint64 {
	if m != nil {
		return m.Epoch
	}
	return 0
}

func (m *ValidatorDeposit) GetTransactionHash() string {
	if m != nil {
		return m.TransactionHash
	}
	return ""
}

func (m *ValidatorDeposit) GetBlockNumber() uint64 {
	if m != nil {
		return m.BlockNumber
	}
	return 0
}

type ValidatorSlashing struct {
	Validator            string   `protobuf:"bytes,1,opt,name=validator,proto3" json:"validator,omitempty"`
	Epoch                uint64   `protobuf:"varint,2,opt,name=epoch,proto3" json:"epoch,omitempty"`
	Slashings            uint32   `protobuf:"varint,3,opt,name=slashings,proto3" json:"slashings,omitempty"`
	TransactionHash      string   `protobuf:"bytes,4,opt,name=transaction_hash,json=transactionHash,proto3" json:"transaction_hash,omitempty"`
	BlockNumber          uint64   `protobuf:"varint,5,opt,name=block_number,json=blockNumber,proto3" json:"block_number,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ValidatorSlashing) Reset()         { *m = ValidatorSlashing{} }
func (m *ValidatorSlashing) String() string { return proto.CompactTextString(m) }
func (*ValidatorSlashing) ProtoMessage()    {}
func (*ValidatorSlashing) Descriptor() ([]byte, []int) {
	return fileDescriptor_289e7c8aea278311, []int{6}
}
func (m *ValidatorSlashing) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ValidatorSlashing.Unmarshal(m, b)
}
func (m *ValidatorSlashing) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ValidatorSlashing.Marshal(b, m, deterministic)
}
func (m *ValidatorSlashing) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ValidatorSlashing.Merge(m, src)
}
func (m *ValidatorSlashing) XXX_Size() int {
	return xxx_messageInfo_ValidatorSlashing.Size(m)
}
func (m *ValidatorSlashing) XXX_DiscardUnknown() {
	xxx_messageInfo_ValidatorSlashing.DiscardUnknown(m)
}

var xxx_messageInfo_ValidatorSlashing proto.InternalMessageInfo

func (m *ValidatorSlashing) GetValidator() string {
	if m != nil {
		return m.Validator
	}
	return ""
}

func (m *ValidatorSlashing) GetEpoch() uint64 {
	if m != nil {
		return m.Epoch
	}
	return 0
}

func (m *ValidatorSlashing) GetSlashings() uint32 {
	if m != nil {
		return m.Slashings
	}
	return 0
}

func (m *ValidatorSlashing) GetTransactionHash() string {
	if m != nil {
		return m.TransactionHash
	}
	return ""
}

func (m *ValidatorSlashing) GetBlockNumber() uint64 {
	if m != nil {
		return m.BlockNumber
	}
	return 0
}

type ValidatorEvent struct {
	// Types that are valid to be assigned to Event:
	//	*ValidatorEvent_Delegated
	//	*ValidatorEvent_Undelegated
	//	*ValidatorEvent_Claimed
	//	*ValidatorEvent_Redelegated
	Event                isValidatorEvent_Event `protobuf_oneof:"event"`
	TransactionHash      string                 `protobuf:"bytes,1,opt,name=transaction_hash,json=transactionHash,proto3" json:"transaction_hash,omitempty"`
	BlockNumber          uint64                 `protobuf:"varint,2,opt,name=block_number,json=blockNumber,proto3" json:"block_number,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *ValidatorEvent) Reset()         { *m = ValidatorEvent{} }
func (m *ValidatorEvent) String() string { return proto.CompactTextString(m) }
func (*ValidatorEvent) ProtoMessage()    {}
func (*ValidatorEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_289e7c8aea278311, []int{7}
}
func (m *ValidatorEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ValidatorEvent.Unmarshal(m, b)
}
func (m *ValidatorEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ValidatorEvent.Marshal(b, m, deterministic)
}
func (m *ValidatorEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ValidatorEvent.Merge(m, src)
}
func (m *ValidatorEvent) XXX_Size() int {
	return xxx_messageInfo_ValidatorEvent.Size(m)
}
func (m *ValidatorEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_ValidatorEvent.DiscardUnknown(m)
}

var xxx_messageInfo_ValidatorEvent proto.InternalMessageInfo

type isValidatorEvent_Event interface {
	isValidatorEvent_Event()
}

type ValidatorEvent_Delegated struct {
	Delegated *ValidatorEvent_EventFields `protobuf:"bytes,100,opt,name=delegated,proto3,oneof" json:"delegated,omitempty"`
}
type ValidatorEvent_Undelegated struct {
	Undelegated *ValidatorEvent_EventFields `protobuf:"bytes,101,opt,name=undelegated,proto3,oneof" json:"undelegated,omitempty"`
}
type ValidatorEvent_Claimed struct {
	Claimed *ValidatorEvent_EventFields `protobuf:"bytes,102,opt,name=claimed,proto3,oneof" json:"claimed,omitempty"`
}
type ValidatorEvent_Redelegated struct {
	Redelegated *ValidatorEvent_EventFields `protobuf:"bytes,103,opt,name=redelegated,proto3,oneof" json:"redelegated,omitempty"`
}

func (*ValidatorEvent_Delegated) isValidatorEvent_Event()   {}
func (*ValidatorEvent_Undelegated) isValidatorEvent_Event() {}
func (*ValidatorEvent_Claimed) isValidatorEvent_Event()     {}
func (*ValidatorEvent_Redelegated) isValidatorEvent_Event() {}

func (m *ValidatorEvent) GetEvent() isValidatorEvent_Event {
	if m != nil {
		return m.Event
	}
	return nil
}

func (m *ValidatorEvent) GetDelegated() *ValidatorEvent_EventFields {
	if x, ok := m.GetEvent().(*ValidatorEvent_Delegated); ok {
		return x.Delegated
	}
	return nil
}

func (m *ValidatorEvent) GetUndelegated() *ValidatorEvent_EventFields {
	if x, ok := m.GetEvent().(*ValidatorEvent_Undelegated); ok {
		return x.Undelegated
	}
	return nil
}

func (m *ValidatorEvent) GetClaimed() *ValidatorEvent_EventFields {
	if x, ok := m.GetEvent().(*ValidatorEvent_Claimed); ok {
		return x.Claimed
	}
	return nil
}

func (m *ValidatorEvent) GetRedelegated() *ValidatorEvent_EventFields {
	if x, ok := m.GetEvent().(*ValidatorEvent_Redelegated); ok {
		return x.Redelegated
	}
	return nil
}

func (m *ValidatorEvent) GetTransactionHash() string {
	if m != nil {
		return m.TransactionHash
	}
	return ""
}

func (m *ValidatorEvent) GetBlockNumber() uint64 {
	if m != nil {
		return m.BlockNumber
	}
	return 0
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*ValidatorEvent) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*ValidatorEvent_Delegated)(nil),
		(*ValidatorEvent_Undelegated)(nil),
		(*ValidatorEvent_Claimed)(nil),
		(*ValidatorEvent_Redelegated)(nil),
	}
}

type ValidatorEvent_EventFields struct {
	Validator            string   `protobuf:"bytes,1,opt,name=validator,proto3" json:"validator,omitempty"`
	Staker               string   `protobuf:"bytes,2,opt,name=staker,proto3" json:"staker,omitempty"`
	Amount               string   `protobuf:"bytes,3,opt,name=amount,proto3" json:"amount,omitempty"`
	Dust                 string   `protobuf:"bytes,4,opt,name=dust,proto3" json:"dust,omitempty"`
	Epoch                uint64   `protobuf:"varint,5,opt,name=epoch,proto3" json:"epoch,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ValidatorEvent_EventFields) Reset()         { *m = ValidatorEvent_EventFields{} }
func (m *ValidatorEvent_EventFields) String() string { return proto.CompactTextString(m) }
func (*ValidatorEvent_EventFields) ProtoMessage()    {}
func (*ValidatorEvent_EventFields) Descriptor() ([]byte, []int) {
	return fileDescriptor_289e7c8aea278311, []int{7, 0}
}
func (m *ValidatorEvent_EventFields) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ValidatorEvent_EventFields.Unmarshal(m, b)
}
func (m *ValidatorEvent_EventFields) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ValidatorEvent_EventFields.Marshal(b, m, deterministic)
}
func (m *ValidatorEvent_EventFields) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ValidatorEvent_EventFields.Merge(m, src)
}
func (m *ValidatorEvent_EventFields) XXX_Size() int {
	return xxx_messageInfo_ValidatorEvent_EventFields.Size(m)
}
func (m *ValidatorEvent_EventFields) XXX_DiscardUnknown() {
	xxx_messageInfo_ValidatorEvent_EventFields.DiscardUnknown(m)
}

var xxx_messageInfo_ValidatorEvent_EventFields proto.InternalMessageInfo

func (m *ValidatorEvent_EventFields) GetValidator() string {
	if m != nil {
		return m.Validator
	}
	return ""
}

func (m *ValidatorEvent_EventFields) GetStaker() string {
	if m != nil {
		return m.Staker
	}
	return ""
}

func (m *ValidatorEvent_EventFields) GetAmount() string {
	if m != nil {
		return m.Amount
	}
	return ""
}

func (m *ValidatorEvent_EventFields) GetDust() string {
	if m != nil {
		return m.Dust
	}
	return ""
}

func (m *ValidatorEvent_EventFields) GetEpoch() uint64 {
	if m != nil {
		return m.Epoch
	}
	return 0
}

type Delegator struct {
	Staker               string   `protobuf:"bytes,1,opt,name=staker,proto3" json:"staker,omitempty"`
	TotalDelegated       string   `protobuf:"bytes,2,opt,name=total_delegated,json=totalDelegated,proto3" json:"total_delegated,omitempty"`
	Epoch                uint64   `protobuf:"varint,3,opt,name=epoch,proto3" json:"epoch,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Delegator) Reset()         { *m = Delegator{} }
func (m *Delegator) String() string { return proto.CompactTextString(m) }
func (*Delegator) ProtoMessage()    {}
func (*Delegator) Descriptor() ([]byte, []int) {
	return fileDescriptor_289e7c8aea278311, []int{8}
}
func (m *Delegator) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Delegator.Unmarshal(m, b)
}
func (m *Delegator) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Delegator.Marshal(b, m, deterministic)
}
func (m *Delegator) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Delegator.Merge(m, src)
}
func (m *Delegator) XXX_Size() int {
	return xxx_messageInfo_Delegator.Size(m)
}
func (m *Delegator) XXX_DiscardUnknown() {
	xxx_messageInfo_Delegator.DiscardUnknown(m)
}

var xxx_messageInfo_Delegator proto.InternalMessageInfo

func (m *Delegator) GetStaker() string {
	if m != nil {
		return m.Staker
	}
	return ""
}

func (m *Delegator) GetTotalDelegated() string {
	if m != nil {
		return m.TotalDelegated
	}
	return ""
}

func (m *Delegator) GetEpoch() uint64 {
	if m != nil {
		return m.Epoch
	}
	return 0
}

type GetValidatorsRequest struct {
	Offset               uint32   `protobuf:"varint,1,opt,name=offset,proto3" json:"offset,omitempty"`
	Size_                uint32   `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetValidatorsRequest) Reset()         { *m = GetValidatorsRequest{} }
func (m *GetValidatorsRequest) String() string { return proto.CompactTextString(m) }
func (*GetValidatorsRequest) ProtoMessage()    {}
func (*GetValidatorsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_289e7c8aea278311, []int{9}
}
func (m *GetValidatorsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetValidatorsRequest.Unmarshal(m, b)
}
func (m *GetValidatorsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetValidatorsRequest.Marshal(b, m, deterministic)
}
func (m *GetValidatorsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetValidatorsRequest.Merge(m, src)
}
func (m *GetValidatorsRequest) XXX_Size() int {
	return xxx_messageInfo_GetValidatorsRequest.Size(m)
}
func (m *GetValidatorsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetValidatorsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetValidatorsRequest proto.InternalMessageInfo

func (m *GetValidatorsRequest) GetOffset() uint32 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *GetValidatorsRequest) GetSize_() uint32 {
	if m != nil {
		return m.Size_
	}
	return 0
}

type GetValidatorsReply struct {
	Validators           []*Validator `protobuf:"bytes,1,rep,name=validators,proto3" json:"validators,omitempty"`
	HasMore              bool         `protobuf:"varint,2,opt,name=has_more,json=hasMore,proto3" json:"has_more,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *GetValidatorsReply) Reset()         { *m = GetValidatorsReply{} }
func (m *GetValidatorsReply) String() string { return proto.CompactTextString(m) }
func (*GetValidatorsReply) ProtoMessage()    {}
func (*GetValidatorsReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_289e7c8aea278311, []int{10}
}
func (m *GetValidatorsReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetValidatorsReply.Unmarshal(m, b)
}
func (m *GetValidatorsReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetValidatorsReply.Marshal(b, m, deterministic)
}
func (m *GetValidatorsReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetValidatorsReply.Merge(m, src)
}
func (m *GetValidatorsReply) XXX_Size() int {
	return xxx_messageInfo_GetValidatorsReply.Size(m)
}
func (m *GetValidatorsReply) XXX_DiscardUnknown() {
	xxx_messageInfo_GetValidatorsReply.DiscardUnknown(m)
}

var xxx_messageInfo_GetValidatorsReply proto.InternalMessageInfo

func (m *GetValidatorsReply) GetValidators() []*Validator {
	if m != nil {
		return m.Validators
	}
	return nil
}

func (m *GetValidatorsReply) GetHasMore() bool {
	if m != nil {
		return m.HasMore
	}
	return false
}

type GetValidatorHistoryRequest struct {
	Offset               uint32   `protobuf:"varint,1,opt,name=offset,proto3" json:"offset,omitempty"`
	Size_                uint32   `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	Validator            string   `protobuf:"bytes,3,opt,name=validator,proto3" json:"validator,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetValidatorHistoryRequest) Reset()         { *m = GetValidatorHistoryRequest{} }
func (m *GetValidatorHistoryRequest) String() string { return proto.CompactTextString(m) }
func (*GetValidatorHistoryRequest) ProtoMessage()    {}
func (*GetValidatorHistoryRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_289e7c8aea278311, []int{11}
}
func (m *GetValidatorHistoryRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetValidatorHistoryRequest.Unmarshal(m, b)
}
func (m *GetValidatorHistoryRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetValidatorHistoryRequest.Marshal(b, m, deterministic)
}
func (m *GetValidatorHistoryRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetValidatorHistoryRequest.Merge(m, src)
}
func (m *GetValidatorHistoryRequest) XXX_Size() int {
	return xxx_messageInfo_GetValidatorHistoryRequest.Size(m)
}
func (m *GetValidatorHistoryRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetValidatorHistoryRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetValidatorHistoryRequest proto.InternalMessageInfo

func (m *GetValidatorHistoryRequest) GetOffset() uint32 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *GetValidatorHistoryRequest) GetSize_() uint32 {
	if m != nil {
		return m.Size_
	}
	return 0
}

func (m *GetValidatorHistoryRequest) GetValidator() string {
	if m != nil {
		return m.Validator
	}
	return ""
}

type GetValidatorHistoryReply struct {
	ValidatorHistories   []*ValidatorHistory `protobuf:"bytes,1,rep,name=validator_histories,json=validatorHistories,proto3" json:"validator_histories,omitempty"`
	HasMore              bool                `protobuf:"varint,2,opt,name=has_more,json=hasMore,proto3" json:"has_more,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *GetValidatorHistoryReply) Reset()         { *m = GetValidatorHistoryReply{} }
func (m *GetValidatorHistoryReply) String() string { return proto.CompactTextString(m) }
func (*GetValidatorHistoryReply) ProtoMessage()    {}
func (*GetValidatorHistoryReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_289e7c8aea278311, []int{12}
}
func (m *GetValidatorHistoryReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetValidatorHistoryReply.Unmarshal(m, b)
}
func (m *GetValidatorHistoryReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetValidatorHistoryReply.Marshal(b, m, deterministic)
}
func (m *GetValidatorHistoryReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetValidatorHistoryReply.Merge(m, src)
}
func (m *GetValidatorHistoryReply) XXX_Size() int {
	return xxx_messageInfo_GetValidatorHistoryReply.Size(m)
}
func (m *GetValidatorHistoryReply) XXX_DiscardUnknown() {
	xxx_messageInfo_GetValidatorHistoryReply.DiscardUnknown(m)
}

var xxx_messageInfo_GetValidatorHistoryReply proto.InternalMessageInfo

func (m *GetValidatorHistoryReply) GetValidatorHistories() []*ValidatorHistory {
	if m != nil {
		return m.ValidatorHistories
	}
	return nil
}

func (m *GetValidatorHistoryReply) GetHasMore() bool {
	if m != nil {
		return m.HasMore
	}
	return false
}

type GetValidatorSlashingsRequest struct {
	Offset               uint32   `protobuf:"varint,1,opt,name=offset,proto3" json:"offset,omitempty"`
	Size_                uint32   `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	Validator            string   `protobuf:"bytes,3,opt,name=validator,proto3" json:"validator,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetValidatorSlashingsRequest) Reset()         { *m = GetValidatorSlashingsRequest{} }
func (m *GetValidatorSlashingsRequest) String() string { return proto.CompactTextString(m) }
func (*GetValidatorSlashingsRequest) ProtoMessage()    {}
func (*GetValidatorSlashingsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_289e7c8aea278311, []int{13}
}
func (m *GetValidatorSlashingsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetValidatorSlashingsRequest.Unmarshal(m, b)
}
func (m *GetValidatorSlashingsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetValidatorSlashingsRequest.Marshal(b, m, deterministic)
}
func (m *GetValidatorSlashingsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetValidatorSlashingsRequest.Merge(m, src)
}
func (m *GetValidatorSlashingsRequest) XXX_Size() int {
	return xxx_messageInfo_GetValidatorSlashingsRequest.Size(m)
}
func (m *GetValidatorSlashingsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetValidatorSlashingsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetValidatorSlashingsRequest proto.InternalMessageInfo

func (m *GetValidatorSlashingsRequest) GetOffset() uint32 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *GetValidatorSlashingsRequest) GetSize_() uint32 {
	if m != nil {
		return m.Size_
	}
	return 0
}

func (m *GetValidatorSlashingsRequest) GetValidator() string {
	if m != nil {
		return m.Validator
	}
	return ""
}

type GetValidatorSlashingsReply struct {
	ValidatorSlashings   []*ValidatorSlashing `protobuf:"bytes,1,rep,name=validator_slashings,json=validatorSlashings,proto3" json:"validator_slashings,omitempty"`
	HasMore              bool                 `protobuf:"varint,2,opt,name=has_more,json=hasMore,proto3" json:"has_more,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *GetValidatorSlashingsReply) Reset()         { *m = GetValidatorSlashingsReply{} }
func (m *GetValidatorSlashingsReply) String() string { return proto.CompactTextString(m) }
func (*GetValidatorSlashingsReply) ProtoMessage()    {}
func (*GetValidatorSlashingsReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_289e7c8aea278311, []int{14}
}
func (m *GetValidatorSlashingsReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetValidatorSlashingsReply.Unmarshal(m, b)
}
func (m *GetValidatorSlashingsReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetValidatorSlashingsReply.Marshal(b, m, deterministic)
}
func (m *GetValidatorSlashingsReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetValidatorSlashingsReply.Merge(m, src)
}
func (m *GetValidatorSlashingsReply) XXX_Size() int {
	return xxx_messageInfo_GetValidatorSlashingsReply.Size(m)
}
func (m *GetValidatorSlashingsReply) XXX_DiscardUnknown() {
	xxx_messageInfo_GetValidatorSlashingsReply.DiscardUnknown(m)
}

var xxx_messageInfo_GetValidatorSlashingsReply proto.InternalMessageInfo

func (m *GetValidatorSlashingsReply) GetValidatorSlashings() []*ValidatorSlashing {
	if m != nil {
		return m.ValidatorSlashings
	}
	return nil
}

func (m *GetValidatorSlashingsReply) GetHasMore() bool {
	if m != nil {
		return m.HasMore
	}
	return false
}

type GetValidatorDepositsRequest struct {
	Offset               uint32   `protobuf:"varint,1,opt,name=offset,proto3" json:"offset,omitempty"`
	Size_                uint32   `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	Validator            string   `protobuf:"bytes,3,opt,name=validator,proto3" json:"validator,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetValidatorDepositsRequest) Reset()         { *m = GetValidatorDepositsRequest{} }
func (m *GetValidatorDepositsRequest) String() string { return proto.CompactTextString(m) }
func (*GetValidatorDepositsRequest) ProtoMessage()    {}
func (*GetValidatorDepositsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_289e7c8aea278311, []int{15}
}
func (m *GetValidatorDepositsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetValidatorDepositsRequest.Unmarshal(m, b)
}
func (m *GetValidatorDepositsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetValidatorDepositsRequest.Marshal(b, m, deterministic)
}
func (m *GetValidatorDepositsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetValidatorDepositsRequest.Merge(m, src)
}
func (m *GetValidatorDepositsRequest) XXX_Size() int {
	return xxx_messageInfo_GetValidatorDepositsRequest.Size(m)
}
func (m *GetValidatorDepositsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetValidatorDepositsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetValidatorDepositsRequest proto.InternalMessageInfo

func (m *GetValidatorDepositsRequest) GetOffset() uint32 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *GetValidatorDepositsRequest) GetSize_() uint32 {
	if m != nil {
		return m.Size_
	}
	return 0
}

func (m *GetValidatorDepositsRequest) GetValidator() string {
	if m != nil {
		return m.Validator
	}
	return ""
}

type GetValidatorDepositsReply struct {
	ValidatorDeposits    []*ValidatorDeposit `protobuf:"bytes,1,rep,name=validator_deposits,json=validatorDeposits,proto3" json:"validator_deposits,omitempty"`
	HasMore              bool                `protobuf:"varint,2,opt,name=has_more,json=hasMore,proto3" json:"has_more,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *GetValidatorDepositsReply) Reset()         { *m = GetValidatorDepositsReply{} }
func (m *GetValidatorDepositsReply) String() string { return proto.CompactTextString(m) }
func (*GetValidatorDepositsReply) ProtoMessage()    {}
func (*GetValidatorDepositsReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_289e7c8aea278311, []int{16}
}
func (m *GetValidatorDepositsReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetValidatorDepositsReply.Unmarshal(m, b)
}
func (m *GetValidatorDepositsReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetValidatorDepositsReply.Marshal(b, m, deterministic)
}
func (m *GetValidatorDepositsReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetValidatorDepositsReply.Merge(m, src)
}
func (m *GetValidatorDepositsReply) XXX_Size() int {
	return xxx_messageInfo_GetValidatorDepositsReply.Size(m)
}
func (m *GetValidatorDepositsReply) XXX_DiscardUnknown() {
	xxx_messageInfo_GetValidatorDepositsReply.DiscardUnknown(m)
}

var xxx_messageInfo_GetValidatorDepositsReply proto.InternalMessageInfo

func (m *GetValidatorDepositsReply) GetValidatorDeposits() []*ValidatorDeposit {
	if m != nil {
		return m.ValidatorDeposits
	}
	return nil
}

func (m *GetValidatorDepositsReply) GetHasMore() bool {
	if m != nil {
		return m.HasMore
	}
	return false
}

type GetValidatorEventsRequest struct {
	Offset               uint32   `protobuf:"varint,1,opt,name=offset,proto3" json:"offset,omitempty"`
	Size_                uint32   `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	Validator            string   `protobuf:"bytes,3,opt,name=validator,proto3" json:"validator,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetValidatorEventsRequest) Reset()         { *m = GetValidatorEventsRequest{} }
func (m *GetValidatorEventsRequest) String() string { return proto.CompactTextString(m) }
func (*GetValidatorEventsRequest) ProtoMessage()    {}
func (*GetValidatorEventsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_289e7c8aea278311, []int{17}
}
func (m *GetValidatorEventsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetValidatorEventsRequest.Unmarshal(m, b)
}
func (m *GetValidatorEventsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetValidatorEventsRequest.Marshal(b, m, deterministic)
}
func (m *GetValidatorEventsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetValidatorEventsRequest.Merge(m, src)
}
func (m *GetValidatorEventsRequest) XXX_Size() int {
	return xxx_messageInfo_GetValidatorEventsRequest.Size(m)
}
func (m *GetValidatorEventsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetValidatorEventsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetValidatorEventsRequest proto.InternalMessageInfo

func (m *GetValidatorEventsRequest) GetOffset() uint32 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *GetValidatorEventsRequest) GetSize_() uint32 {
	if m != nil {
		return m.Size_
	}
	return 0
}

func (m *GetValidatorEventsRequest) GetValidator() string {
	if m != nil {
		return m.Validator
	}
	return ""
}

type GetValidatorEventsReply struct {
	ValidatorEvents      []*ValidatorEvent `protobuf:"bytes,1,rep,name=validator_events,json=validatorEvents,proto3" json:"validator_events,omitempty"`
	HasMore              bool              `protobuf:"varint,2,opt,name=has_more,json=hasMore,proto3" json:"has_more,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *GetValidatorEventsReply) Reset()         { *m = GetValidatorEventsReply{} }
func (m *GetValidatorEventsReply) String() string { return proto.CompactTextString(m) }
func (*GetValidatorEventsReply) ProtoMessage()    {}
func (*GetValidatorEventsReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_289e7c8aea278311, []int{18}
}
func (m *GetValidatorEventsReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetValidatorEventsReply.Unmarshal(m, b)
}
func (m *GetValidatorEventsReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetValidatorEventsReply.Marshal(b, m, deterministic)
}
func (m *GetValidatorEventsReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetValidatorEventsReply.Merge(m, src)
}
func (m *GetValidatorEventsReply) XXX_Size() int {
	return xxx_messageInfo_GetValidatorEventsReply.Size(m)
}
func (m *GetValidatorEventsReply) XXX_DiscardUnknown() {
	xxx_messageInfo_GetValidatorEventsReply.DiscardUnknown(m)
}

var xxx_messageInfo_GetValidatorEventsReply proto.InternalMessageInfo

func (m *GetValidatorEventsReply) GetValidatorEvents() []*ValidatorEvent {
	if m != nil {
		return m.ValidatorEvents
	}
	return nil
}

func (m *GetValidatorEventsReply) GetHasMore() bool {
	if m != nil {
		return m.HasMore
	}
	return false
}

type GetChainsRequest struct {
	Offset               uint32   `protobuf:"varint,1,opt,name=offset,proto3" json:"offset,omitempty"`
	Size_                uint32   `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	Chain                string   `protobuf:"bytes,3,opt,name=chain,proto3" json:"chain,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetChainsRequest) Reset()         { *m = GetChainsRequest{} }
func (m *GetChainsRequest) String() string { return proto.CompactTextString(m) }
func (*GetChainsRequest) ProtoMessage()    {}
func (*GetChainsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_289e7c8aea278311, []int{19}
}
func (m *GetChainsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetChainsRequest.Unmarshal(m, b)
}
func (m *GetChainsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetChainsRequest.Marshal(b, m, deterministic)
}
func (m *GetChainsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetChainsRequest.Merge(m, src)
}
func (m *GetChainsRequest) XXX_Size() int {
	return xxx_messageInfo_GetChainsRequest.Size(m)
}
func (m *GetChainsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetChainsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetChainsRequest proto.InternalMessageInfo

func (m *GetChainsRequest) GetOffset() uint32 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *GetChainsRequest) GetSize_() uint32 {
	if m != nil {
		return m.Size_
	}
	return 0
}

func (m *GetChainsRequest) GetChain() string {
	if m != nil {
		return m.Chain
	}
	return ""
}

type GetChainsReply struct {
	Chains               []*Chain `protobuf:"bytes,1,rep,name=chains,proto3" json:"chains,omitempty"`
	HasMore              bool     `protobuf:"varint,2,opt,name=has_more,json=hasMore,proto3" json:"has_more,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetChainsReply) Reset()         { *m = GetChainsReply{} }
func (m *GetChainsReply) String() string { return proto.CompactTextString(m) }
func (*GetChainsReply) ProtoMessage()    {}
func (*GetChainsReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_289e7c8aea278311, []int{20}
}
func (m *GetChainsReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetChainsReply.Unmarshal(m, b)
}
func (m *GetChainsReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetChainsReply.Marshal(b, m, deterministic)
}
func (m *GetChainsReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetChainsReply.Merge(m, src)
}
func (m *GetChainsReply) XXX_Size() int {
	return xxx_messageInfo_GetChainsReply.Size(m)
}
func (m *GetChainsReply) XXX_DiscardUnknown() {
	xxx_messageInfo_GetChainsReply.DiscardUnknown(m)
}

var xxx_messageInfo_GetChainsReply proto.InternalMessageInfo

func (m *GetChainsReply) GetChains() []*Chain {
	if m != nil {
		return m.Chains
	}
	return nil
}

func (m *GetChainsReply) GetHasMore() bool {
	if m != nil {
		return m.HasMore
	}
	return false
}

type GetDelegatorsRequest struct {
	Offset               uint32   `protobuf:"varint,1,opt,name=offset,proto3" json:"offset,omitempty"`
	Size_                uint32   `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	Validator            string   `protobuf:"bytes,3,opt,name=validator,proto3" json:"validator,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetDelegatorsRequest) Reset()         { *m = GetDelegatorsRequest{} }
func (m *GetDelegatorsRequest) String() string { return proto.CompactTextString(m) }
func (*GetDelegatorsRequest) ProtoMessage()    {}
func (*GetDelegatorsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_289e7c8aea278311, []int{21}
}
func (m *GetDelegatorsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetDelegatorsRequest.Unmarshal(m, b)
}
func (m *GetDelegatorsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetDelegatorsRequest.Marshal(b, m, deterministic)
}
func (m *GetDelegatorsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetDelegatorsRequest.Merge(m, src)
}
func (m *GetDelegatorsRequest) XXX_Size() int {
	return xxx_messageInfo_GetDelegatorsRequest.Size(m)
}
func (m *GetDelegatorsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetDelegatorsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetDelegatorsRequest proto.InternalMessageInfo

func (m *GetDelegatorsRequest) GetOffset() uint32 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *GetDelegatorsRequest) GetSize_() uint32 {
	if m != nil {
		return m.Size_
	}
	return 0
}

func (m *GetDelegatorsRequest) GetValidator() string {
	if m != nil {
		return m.Validator
	}
	return ""
}

type GetDelegatorsReply struct {
	Delegators           []*Delegator `protobuf:"bytes,1,rep,name=delegators,proto3" json:"delegators,omitempty"`
	HasMore              bool         `protobuf:"varint,2,opt,name=has_more,json=hasMore,proto3" json:"has_more,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *GetDelegatorsReply) Reset()         { *m = GetDelegatorsReply{} }
func (m *GetDelegatorsReply) String() string { return proto.CompactTextString(m) }
func (*GetDelegatorsReply) ProtoMessage()    {}
func (*GetDelegatorsReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_289e7c8aea278311, []int{22}
}
func (m *GetDelegatorsReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetDelegatorsReply.Unmarshal(m, b)
}
func (m *GetDelegatorsReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetDelegatorsReply.Marshal(b, m, deterministic)
}
func (m *GetDelegatorsReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetDelegatorsReply.Merge(m, src)
}
func (m *GetDelegatorsReply) XXX_Size() int {
	return xxx_messageInfo_GetDelegatorsReply.Size(m)
}
func (m *GetDelegatorsReply) XXX_DiscardUnknown() {
	xxx_messageInfo_GetDelegatorsReply.DiscardUnknown(m)
}

var xxx_messageInfo_GetDelegatorsReply proto.InternalMessageInfo

func (m *GetDelegatorsReply) GetDelegators() []*Delegator {
	if m != nil {
		return m.Delegators
	}
	return nil
}

func (m *GetDelegatorsReply) GetHasMore() bool {
	if m != nil {
		return m.HasMore
	}
	return false
}

func init() {
	proto.RegisterEnum("com.ankr.ValidatorStatus", ValidatorStatus_name, ValidatorStatus_value)
	proto.RegisterType((*ChainNativeCurrency)(nil), "com.ankr.ChainNativeCurrency")
	proto.RegisterType((*ChainExplorer)(nil), "com.ankr.ChainExplorer")
	proto.RegisterType((*Chain)(nil), "com.ankr.Chain")
	proto.RegisterType((*Validator)(nil), "com.ankr.Validator")
	proto.RegisterType((*ValidatorHistory)(nil), "com.ankr.ValidatorHistory")
	proto.RegisterType((*ValidatorDeposit)(nil), "com.ankr.ValidatorDeposit")
	proto.RegisterType((*ValidatorSlashing)(nil), "com.ankr.ValidatorSlashing")
	proto.RegisterType((*ValidatorEvent)(nil), "com.ankr.ValidatorEvent")
	proto.RegisterType((*ValidatorEvent_EventFields)(nil), "com.ankr.ValidatorEvent.EventFields")
	proto.RegisterType((*Delegator)(nil), "com.ankr.Delegator")
	proto.RegisterType((*GetValidatorsRequest)(nil), "com.ankr.GetValidatorsRequest")
	proto.RegisterType((*GetValidatorsReply)(nil), "com.ankr.GetValidatorsReply")
	proto.RegisterType((*GetValidatorHistoryRequest)(nil), "com.ankr.GetValidatorHistoryRequest")
	proto.RegisterType((*GetValidatorHistoryReply)(nil), "com.ankr.GetValidatorHistoryReply")
	proto.RegisterType((*GetValidatorSlashingsRequest)(nil), "com.ankr.GetValidatorSlashingsRequest")
	proto.RegisterType((*GetValidatorSlashingsReply)(nil), "com.ankr.GetValidatorSlashingsReply")
	proto.RegisterType((*GetValidatorDepositsRequest)(nil), "com.ankr.GetValidatorDepositsRequest")
	proto.RegisterType((*GetValidatorDepositsReply)(nil), "com.ankr.GetValidatorDepositsReply")
	proto.RegisterType((*GetValidatorEventsRequest)(nil), "com.ankr.GetValidatorEventsRequest")
	proto.RegisterType((*GetValidatorEventsReply)(nil), "com.ankr.GetValidatorEventsReply")
	proto.RegisterType((*GetChainsRequest)(nil), "com.ankr.GetChainsRequest")
	proto.RegisterType((*GetChainsReply)(nil), "com.ankr.GetChainsReply")
	proto.RegisterType((*GetDelegatorsRequest)(nil), "com.ankr.GetDelegatorsRequest")
	proto.RegisterType((*GetDelegatorsReply)(nil), "com.ankr.GetDelegatorsReply")
}

func init() { proto.RegisterFile("staking.proto", fileDescriptor_289e7c8aea278311) }

var fileDescriptor_289e7c8aea278311 = []byte{
	// 1249 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x57, 0x4d, 0x73, 0xdb, 0xc4,
	0x1b, 0xaf, 0x62, 0x3b, 0xb6, 0x1f, 0xff, 0xfd, 0xd2, 0x4d, 0xfa, 0xaf, 0xa2, 0xa6, 0x25, 0x15,
	0x85, 0x06, 0x66, 0x70, 0x87, 0xf4, 0xd8, 0x0b, 0x4e, 0x9c, 0x26, 0x86, 0xd6, 0x2d, 0x8a, 0xdb,
	0x03, 0x03, 0x23, 0xd6, 0xd2, 0xc6, 0x16, 0x95, 0x25, 0xa3, 0x5d, 0xbb, 0x98, 0x1b, 0xcc, 0x74,
	0x38, 0x30, 0xc3, 0x37, 0xe0, 0x03, 0x30, 0xc3, 0x8d, 0x8f, 0xc7, 0x85, 0xd9, 0xd5, 0xea, 0xcd,
	0x56, 0x9c, 0xb6, 0xd3, 0x5e, 0x3c, 0xfb, 0xbc, 0xff, 0x7e, 0xcf, 0xee, 0x3e, 0x2b, 0x43, 0x9d,
	0x32, 0xfc, 0xc2, 0xf1, 0x46, 0xed, 0x69, 0xe0, 0x33, 0x1f, 0x55, 0x2c, 0x7f, 0xd2, 0xc6, 0xde,
	0x8b, 0x40, 0xff, 0x0e, 0xb6, 0x8e, 0xc6, 0xd8, 0xf1, 0xfa, 0x98, 0x39, 0x73, 0x72, 0x34, 0x0b,
	0x02, 0xe2, 0x59, 0x0b, 0x84, 0xa0, 0xe8, 0xe1, 0x09, 0x51, 0x95, 0x3d, 0x65, 0xbf, 0x6a, 0x88,
	0x35, 0xfa, 0x3f, 0x6c, 0xd2, 0xc5, 0x64, 0xe8, 0xbb, 0xea, 0x86, 0xd0, 0x4a, 0x09, 0x69, 0x50,
	0xb1, 0x89, 0xe5, 0x4c, 0xb0, 0x4b, 0xd5, 0xc2, 0x9e, 0xb2, 0x5f, 0x37, 0x62, 0x59, 0xff, 0x1a,
	0xea, 0x22, 0xfd, 0xf1, 0x4f, 0x53, 0xd7, 0x0f, 0x48, 0x90, 0x9b, 0xb8, 0x05, 0x85, 0x59, 0x10,
	0x65, 0xe5, 0x4b, 0x9e, 0x92, 0x32, 0xec, 0xd9, 0x38, 0xb0, 0x45, 0xca, 0xaa, 0x11, 0xcb, 0xfa,
	0x9f, 0x1b, 0x50, 0x12, 0x39, 0xd1, 0x0e, 0x54, 0x2c, 0xbe, 0x30, 0x1d, 0x5b, 0xe4, 0x2b, 0x1a,
	0x65, 0x21, 0xf7, 0x6c, 0xf4, 0x01, 0xd4, 0xa6, 0x81, 0xff, 0x03, 0xb1, 0x98, 0x99, 0xa4, 0x06,
	0xa9, 0x7a, 0x16, 0xb8, 0x31, 0x8e, 0x42, 0x0a, 0xc7, 0x4d, 0x00, 0x3a, 0xf6, 0x03, 0x66, 0x0a,
	0x4b, 0x51, 0x58, 0xaa, 0x42, 0xd3, 0x97, 0x30, 0x83, 0xa9, 0xa5, 0x96, 0xf6, 0x0a, 0x1c, 0x66,
	0x30, 0xb5, 0x78, 0x47, 0xce, 0xf1, 0xcc, 0x22, 0x4c, 0xdd, 0x14, 0x4a, 0x29, 0xa1, 0x87, 0xd0,
	0xf4, 0x44, 0x3f, 0x4d, 0x4b, 0x36, 0x54, 0x2d, 0xef, 0x29, 0xfb, 0xb5, 0x83, 0x9b, 0xed, 0xa8,
	0xf1, 0xed, 0x9c, 0xae, 0x1b, 0x0d, 0x2f, 0xbb, 0x0b, 0xf7, 0xa1, 0x42, 0x64, 0xe3, 0xd4, 0xca,
	0x5e, 0x61, 0xbf, 0x76, 0x70, 0x7d, 0x29, 0x41, 0xd4, 0x57, 0x23, 0x76, 0xd4, 0xff, 0x50, 0xa0,
	0xfa, 0x1c, 0xbb, 0x8e, 0x8d, 0x99, 0x1f, 0x20, 0x15, 0xca, 0xd8, 0xb6, 0x03, 0x42, 0xa9, 0x6c,
	0x79, 0x24, 0xa2, 0x6d, 0x28, 0xf9, 0x2f, 0x3d, 0x12, 0xc8, 0xe6, 0x84, 0x02, 0xfa, 0x1c, 0x36,
	0x29, 0xc3, 0x6c, 0x16, 0x6e, 0x65, 0xe3, 0x60, 0x27, 0x29, 0x18, 0x27, 0x3d, 0x13, 0x0e, 0x86,
	0x74, 0x44, 0xb7, 0x00, 0x2c, 0x7f, 0x32, 0x71, 0x28, 0x75, 0x7c, 0x4f, 0xb4, 0xad, 0x6e, 0xa4,
	0x34, 0xfa, 0x5f, 0x0a, 0xb4, 0xe2, 0xd8, 0x53, 0x87, 0x32, 0x3f, 0x58, 0xac, 0xc1, 0xf5, 0x19,
	0xf0, 0x5d, 0xf4, 0x46, 0x84, 0x0a, 0x64, 0xb5, 0x83, 0xad, 0x1c, 0x08, 0x46, 0xe4, 0x83, 0x3e,
	0x81, 0x16, 0x0b, 0xb0, 0x47, 0xb1, 0xc5, 0x1c, 0xdf, 0x33, 0xc7, 0x98, 0x8e, 0xe5, 0xa6, 0x36,
	0x53, 0xfa, 0x53, 0x4c, 0xc7, 0xe8, 0x36, 0xfc, 0x6f, 0xe8, 0xfa, 0xd6, 0x0b, 0xd3, 0x9b, 0x4d,
	0x86, 0x24, 0x10, 0x50, 0x8b, 0x46, 0x4d, 0xe8, 0xfa, 0x42, 0xa5, 0xff, 0x9d, 0xc6, 0xda, 0x25,
	0x53, 0x9f, 0x3a, 0x0c, 0xed, 0x42, 0x75, 0x1e, 0xe9, 0x24, 0xda, 0x44, 0xc1, 0x0f, 0x01, 0x9e,
	0xf8, 0x33, 0x8f, 0x45, 0xd7, 0x22, 0x94, 0x78, 0x7f, 0xc9, 0xd4, 0xb7, 0x42, 0x34, 0x45, 0x23,
	0x14, 0x72, 0xe1, 0x16, 0x5f, 0x0f, 0x6e, 0x69, 0x15, 0xee, 0x3f, 0x0a, 0x5c, 0x4d, 0xb6, 0xc5,
	0xc5, 0x74, 0xec, 0x78, 0xa3, 0x4b, 0xf0, 0xc6, 0xb8, 0x36, 0xd2, 0xb8, 0x76, 0xa1, 0x4a, 0x65,
	0x7c, 0x74, 0x8b, 0x13, 0xc5, 0x3b, 0x46, 0xfd, 0x7b, 0x11, 0x1a, 0x31, 0xea, 0xe3, 0x39, 0xf1,
	0x18, 0xea, 0x42, 0xd5, 0x26, 0x2e, 0x19, 0x61, 0x46, 0x6c, 0xd5, 0x16, 0xdb, 0x7e, 0x27, 0x67,
	0xdb, 0x85, 0x73, 0x5b, 0xfc, 0x3e, 0x74, 0x88, 0x6b, 0xd3, 0xd3, 0x2b, 0x46, 0x12, 0x88, 0x4e,
	0xa1, 0x36, 0xf3, 0x92, 0x3c, 0xe4, 0x8d, 0xf2, 0xa4, 0x43, 0xd1, 0x17, 0x50, 0xb6, 0x5c, 0xec,
	0x4c, 0x88, 0xad, 0x9e, 0xbf, 0x51, 0x96, 0x28, 0x8c, 0x63, 0x09, 0x48, 0x82, 0x65, 0xf4, 0x66,
	0x58, 0x52, 0xa1, 0xb9, 0xcd, 0x57, 0x5e, 0xaf, 0xf9, 0x1b, 0x2b, 0xcd, 0xd7, 0x5e, 0x29, 0x50,
	0x4b, 0x15, 0xbb, 0xfc, 0x70, 0xf3, 0x97, 0x23, 0x9e, 0x12, 0x52, 0x4a, 0x1d, 0xfa, 0x42, 0xe6,
	0xd0, 0x23, 0x28, 0xda, 0x33, 0xca, 0xe4, 0xe1, 0x10, 0xeb, 0xe4, 0xc0, 0x95, 0x52, 0x07, 0xee,
	0xb0, 0x0c, 0x25, 0xc2, 0x61, 0xe8, 0x43, 0xa8, 0x76, 0x43, 0xae, 0x99, 0x7a, 0x4a, 0xa6, 0xde,
	0x5d, 0x68, 0x32, 0x9f, 0x61, 0xd7, 0x4c, 0x3a, 0x1a, 0x02, 0x6a, 0x08, 0x75, 0x37, 0x6e, 0x56,
	0xee, 0xad, 0xd3, 0x0f, 0x61, 0xfb, 0x84, 0xb0, 0xb8, 0xe5, 0xd4, 0x20, 0x3f, 0xce, 0x08, 0x65,
	0xbc, 0x9c, 0x7f, 0x7e, 0x4e, 0x09, 0x13, 0xe5, 0xea, 0x86, 0x94, 0x38, 0x0d, 0xea, 0xfc, 0x4c,
	0x44, 0x8d, 0xba, 0x21, 0xd6, 0xba, 0x0d, 0x68, 0x29, 0xc7, 0xd4, 0xe5, 0x23, 0x1a, 0xe2, 0x6e,
	0xf1, 0x51, 0x56, 0xb8, 0x68, 0x60, 0xa5, 0xdc, 0xf8, 0xc3, 0x35, 0xc6, 0xd4, 0x9c, 0xf8, 0x41,
	0x58, 0xa2, 0x62, 0x94, 0xc7, 0x98, 0x3e, 0xf6, 0x03, 0xa2, 0x9f, 0x83, 0x96, 0xae, 0x22, 0xc7,
	0xe5, 0x5b, 0xe0, 0xcd, 0x6e, 0x6c, 0x61, 0x69, 0x63, 0xf5, 0x5f, 0x15, 0x50, 0x73, 0x0b, 0x71,
	0x52, 0x5f, 0xc1, 0x56, 0xec, 0x69, 0x8e, 0x85, 0xc5, 0x21, 0x11, 0x3b, 0x2d, 0x87, 0x5d, 0x14,
	0x8d, 0xe6, 0x59, 0x8d, 0x43, 0xd6, 0x92, 0x1d, 0xc3, 0x6e, 0x1a, 0x43, 0x34, 0xc0, 0xe8, 0xbb,
	0xa7, 0xfb, 0x4a, 0xc9, 0xf6, 0x35, 0x55, 0x8a, 0x13, 0x7e, 0x94, 0x26, 0x9c, 0xcc, 0xc1, 0x90,
	0xf0, 0x8d, 0xbc, 0x27, 0x50, 0xfa, 0xa4, 0x18, 0xc7, 0x29, 0xd7, 0x31, 0x1e, 0xc1, 0x8d, 0x34,
	0x0c, 0xf9, 0xc2, 0xbc, 0x07, 0xc2, 0xbf, 0x28, 0xb0, 0x93, 0x5f, 0x89, 0xf3, 0xed, 0x41, 0x82,
	0xdb, 0xb4, 0xa5, 0x69, 0xcd, 0xfe, 0xca, 0x68, 0xe3, 0xea, 0x7c, 0x39, 0xdf, 0x3a, 0xb2, 0x24,
	0x0b, 0x41, 0x4c, 0x9d, 0xf7, 0x40, 0x75, 0x01, 0xd7, 0xf3, 0xca, 0x70, 0x9e, 0x47, 0xd0, 0x4a,
	0x78, 0x8a, 0x71, 0x13, 0xb1, 0x54, 0x2f, 0x9a, 0xc4, 0x46, 0x73, 0x9e, 0xcd, 0xb4, 0x8e, 0xe1,
	0x00, 0x5a, 0x27, 0x84, 0x89, 0x2f, 0xb1, 0xb7, 0x22, 0xb6, 0x0d, 0x25, 0xf1, 0xc5, 0x2a, 0x49,
	0x85, 0x82, 0x3e, 0x80, 0x46, 0x2a, 0x2b, 0xe7, 0x71, 0x17, 0x36, 0x85, 0x29, 0x42, 0xdf, 0x5c,
	0xfa, 0x0c, 0x34, 0xa4, 0x79, 0x1d, 0xd6, 0xef, 0xc5, 0x0c, 0x8c, 0x47, 0xed, 0x7b, 0xd8, 0x88,
	0x70, 0x42, 0xa6, 0x2b, 0xc8, 0x09, 0x69, 0xc7, 0xaa, 0xd5, 0x09, 0x19, 0xbb, 0x1b, 0x29, 0xb7,
	0x35, 0x3c, 0x3e, 0xfd, 0x4d, 0x81, 0xe6, 0xd2, 0xa7, 0x28, 0xba, 0x05, 0xda, 0xf3, 0xce, 0xa3,
	0x5e, 0xb7, 0x33, 0x78, 0x62, 0x98, 0x67, 0x83, 0xce, 0xe0, 0xd9, 0x99, 0xd9, 0x7f, 0x32, 0x30,
	0x1f, 0x3e, 0x79, 0xd6, 0xef, 0xb6, 0xae, 0xa0, 0x1b, 0x70, 0x7d, 0xc5, 0xde, 0x39, 0x1a, 0xf4,
	0x9e, 0x1f, 0xb7, 0x14, 0xb4, 0x0b, 0xea, 0x8a, 0xf1, 0xe9, 0x71, 0xbf, 0xdb, 0xeb, 0x9f, 0xb4,
	0x36, 0xd0, 0x0e, 0x5c, 0x5b, 0xb1, 0x7e, 0xd9, 0xe9, 0x3d, 0x6a, 0x15, 0x0e, 0xfe, 0x2d, 0x42,
	0xe3, 0x2c, 0xfc, 0x5f, 0x75, 0x82, 0x19, 0x79, 0x89, 0x17, 0xe8, 0x31, 0xd4, 0x33, 0x8f, 0x04,
	0xba, 0x95, 0x30, 0xcd, 0x7b, 0x81, 0xb4, 0xdd, 0x0b, 0xed, 0xbc, 0x77, 0x26, 0x6c, 0xe5, 0x0c,
	0x69, 0x74, 0x27, 0x3f, 0x28, 0xfb, 0x58, 0x68, 0xfa, 0x25, 0x5e, 0xbc, 0x00, 0x81, 0x6b, 0xb9,
	0x63, 0x11, 0x7d, 0x9c, 0x1f, 0xbc, 0x3c, 0xa2, 0xb5, 0x3b, 0x97, 0xfa, 0xf1, 0x32, 0xc3, 0xec,
	0xfb, 0x1b, 0x0f, 0x8f, 0x8f, 0xf2, 0xa3, 0x97, 0xc6, 0xa2, 0xf6, 0xe1, 0x65, 0x6e, 0xbc, 0xc6,
	0xb7, 0xd9, 0xf7, 0x59, 0x5e, 0xde, 0x0b, 0x42, 0x33, 0xb3, 0x48, 0xbb, 0xbd, 0xde, 0x89, 0x67,
	0xef, 0x40, 0x35, 0xbe, 0x93, 0x48, 0xcb, 0xf8, 0x67, 0xae, 0xbf, 0xa6, 0xe6, 0xda, 0x78, 0x8a,
	0xf0, 0x6c, 0x24, 0xd7, 0x63, 0xe9, 0x6c, 0xac, 0xdc, 0xcc, 0xa5, 0xb3, 0xb1, 0x74, 0xaf, 0x0e,
	0x1f, 0x40, 0x23, 0x36, 0x8b, 0x7f, 0xf5, 0x87, 0x5b, 0xd9, 0xc3, 0xf8, 0x94, 0x2b, 0xbf, 0xd9,
	0x6e, 0xdf, 0xa3, 0x63, 0x1c, 0x10, 0xfb, 0x1e, 0x5b, 0x4c, 0x09, 0x7d, 0x20, 0x7e, 0x87, 0x9b,
	0x22, 0xe2, 0xfe, 0x7f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x6e, 0xe2, 0x32, 0x73, 0x18, 0x10, 0x00,
	0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// StakingGatewayClient is the client API for StakingGateway service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type StakingGatewayClient interface {
	GetValidators(ctx context.Context, in *GetValidatorsRequest, opts ...grpc.CallOption) (*GetValidatorsReply, error)
	GetValidatorHistory(ctx context.Context, in *GetValidatorHistoryRequest, opts ...grpc.CallOption) (*GetValidatorHistoryReply, error)
	GetValidatorSlashings(ctx context.Context, in *GetValidatorSlashingsRequest, opts ...grpc.CallOption) (*GetValidatorSlashingsReply, error)
	GetValidatorDeposits(ctx context.Context, in *GetValidatorDepositsRequest, opts ...grpc.CallOption) (*GetValidatorDepositsReply, error)
	GetValidatorEvents(ctx context.Context, in *GetValidatorEventsRequest, opts ...grpc.CallOption) (*GetValidatorEventsReply, error)
	GetChains(ctx context.Context, in *GetChainsRequest, opts ...grpc.CallOption) (*GetChainsReply, error)
	GetDelegators(ctx context.Context, in *GetDelegatorsRequest, opts ...grpc.CallOption) (*GetDelegatorsReply, error)
}

type stakingGatewayClient struct {
	cc *grpc.ClientConn
}

func NewStakingGatewayClient(cc *grpc.ClientConn) StakingGatewayClient {
	return &stakingGatewayClient{cc}
}

func (c *stakingGatewayClient) GetValidators(ctx context.Context, in *GetValidatorsRequest, opts ...grpc.CallOption) (*GetValidatorsReply, error) {
	out := new(GetValidatorsReply)
	err := c.cc.Invoke(ctx, "/com.ankr.StakingGateway/GetValidators", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stakingGatewayClient) GetValidatorHistory(ctx context.Context, in *GetValidatorHistoryRequest, opts ...grpc.CallOption) (*GetValidatorHistoryReply, error) {
	out := new(GetValidatorHistoryReply)
	err := c.cc.Invoke(ctx, "/com.ankr.StakingGateway/GetValidatorHistory", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stakingGatewayClient) GetValidatorSlashings(ctx context.Context, in *GetValidatorSlashingsRequest, opts ...grpc.CallOption) (*GetValidatorSlashingsReply, error) {
	out := new(GetValidatorSlashingsReply)
	err := c.cc.Invoke(ctx, "/com.ankr.StakingGateway/GetValidatorSlashings", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stakingGatewayClient) GetValidatorDeposits(ctx context.Context, in *GetValidatorDepositsRequest, opts ...grpc.CallOption) (*GetValidatorDepositsReply, error) {
	out := new(GetValidatorDepositsReply)
	err := c.cc.Invoke(ctx, "/com.ankr.StakingGateway/GetValidatorDeposits", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stakingGatewayClient) GetValidatorEvents(ctx context.Context, in *GetValidatorEventsRequest, opts ...grpc.CallOption) (*GetValidatorEventsReply, error) {
	out := new(GetValidatorEventsReply)
	err := c.cc.Invoke(ctx, "/com.ankr.StakingGateway/GetValidatorEvents", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stakingGatewayClient) GetChains(ctx context.Context, in *GetChainsRequest, opts ...grpc.CallOption) (*GetChainsReply, error) {
	out := new(GetChainsReply)
	err := c.cc.Invoke(ctx, "/com.ankr.StakingGateway/GetChains", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stakingGatewayClient) GetDelegators(ctx context.Context, in *GetDelegatorsRequest, opts ...grpc.CallOption) (*GetDelegatorsReply, error) {
	out := new(GetDelegatorsReply)
	err := c.cc.Invoke(ctx, "/com.ankr.StakingGateway/GetDelegators", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StakingGatewayServer is the server API for StakingGateway service.
type StakingGatewayServer interface {
	GetValidators(context.Context, *GetValidatorsRequest) (*GetValidatorsReply, error)
	GetValidatorHistory(context.Context, *GetValidatorHistoryRequest) (*GetValidatorHistoryReply, error)
	GetValidatorSlashings(context.Context, *GetValidatorSlashingsRequest) (*GetValidatorSlashingsReply, error)
	GetValidatorDeposits(context.Context, *GetValidatorDepositsRequest) (*GetValidatorDepositsReply, error)
	GetValidatorEvents(context.Context, *GetValidatorEventsRequest) (*GetValidatorEventsReply, error)
	GetChains(context.Context, *GetChainsRequest) (*GetChainsReply, error)
	GetDelegators(context.Context, *GetDelegatorsRequest) (*GetDelegatorsReply, error)
}

// UnimplementedStakingGatewayServer can be embedded to have forward compatible implementations.
type UnimplementedStakingGatewayServer struct {
}

func (*UnimplementedStakingGatewayServer) GetValidators(ctx context.Context, req *GetValidatorsRequest) (*GetValidatorsReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetValidators not implemented")
}
func (*UnimplementedStakingGatewayServer) GetValidatorHistory(ctx context.Context, req *GetValidatorHistoryRequest) (*GetValidatorHistoryReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetValidatorHistory not implemented")
}
func (*UnimplementedStakingGatewayServer) GetValidatorSlashings(ctx context.Context, req *GetValidatorSlashingsRequest) (*GetValidatorSlashingsReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetValidatorSlashings not implemented")
}
func (*UnimplementedStakingGatewayServer) GetValidatorDeposits(ctx context.Context, req *GetValidatorDepositsRequest) (*GetValidatorDepositsReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetValidatorDeposits not implemented")
}
func (*UnimplementedStakingGatewayServer) GetValidatorEvents(ctx context.Context, req *GetValidatorEventsRequest) (*GetValidatorEventsReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetValidatorEvents not implemented")
}
func (*UnimplementedStakingGatewayServer) GetChains(ctx context.Context, req *GetChainsRequest) (*GetChainsReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetChains not implemented")
}
func (*UnimplementedStakingGatewayServer) GetDelegators(ctx context.Context, req *GetDelegatorsRequest) (*GetDelegatorsReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDelegators not implemented")
}

func RegisterStakingGatewayServer(s *grpc.Server, srv StakingGatewayServer) {
	s.RegisterService(&_StakingGateway_serviceDesc, srv)
}

func _StakingGateway_GetValidators_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetValidatorsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StakingGatewayServer).GetValidators(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/com.ankr.StakingGateway/GetValidators",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StakingGatewayServer).GetValidators(ctx, req.(*GetValidatorsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StakingGateway_GetValidatorHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetValidatorHistoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StakingGatewayServer).GetValidatorHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/com.ankr.StakingGateway/GetValidatorHistory",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StakingGatewayServer).GetValidatorHistory(ctx, req.(*GetValidatorHistoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StakingGateway_GetValidatorSlashings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetValidatorSlashingsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StakingGatewayServer).GetValidatorSlashings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/com.ankr.StakingGateway/GetValidatorSlashings",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StakingGatewayServer).GetValidatorSlashings(ctx, req.(*GetValidatorSlashingsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StakingGateway_GetValidatorDeposits_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetValidatorDepositsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StakingGatewayServer).GetValidatorDeposits(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/com.ankr.StakingGateway/GetValidatorDeposits",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StakingGatewayServer).GetValidatorDeposits(ctx, req.(*GetValidatorDepositsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StakingGateway_GetValidatorEvents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetValidatorEventsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StakingGatewayServer).GetValidatorEvents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/com.ankr.StakingGateway/GetValidatorEvents",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StakingGatewayServer).GetValidatorEvents(ctx, req.(*GetValidatorEventsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StakingGateway_GetChains_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetChainsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StakingGatewayServer).GetChains(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/com.ankr.StakingGateway/GetChains",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StakingGatewayServer).GetChains(ctx, req.(*GetChainsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StakingGateway_GetDelegators_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDelegatorsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StakingGatewayServer).GetDelegators(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/com.ankr.StakingGateway/GetDelegators",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StakingGatewayServer).GetDelegators(ctx, req.(*GetDelegatorsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _StakingGateway_serviceDesc = grpc.ServiceDesc{
	ServiceName: "com.ankr.StakingGateway",
	HandlerType: (*StakingGatewayServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetValidators",
			Handler:    _StakingGateway_GetValidators_Handler,
		},
		{
			MethodName: "GetValidatorHistory",
			Handler:    _StakingGateway_GetValidatorHistory_Handler,
		},
		{
			MethodName: "GetValidatorSlashings",
			Handler:    _StakingGateway_GetValidatorSlashings_Handler,
		},
		{
			MethodName: "GetValidatorDeposits",
			Handler:    _StakingGateway_GetValidatorDeposits_Handler,
		},
		{
			MethodName: "GetValidatorEvents",
			Handler:    _StakingGateway_GetValidatorEvents_Handler,
		},
		{
			MethodName: "GetChains",
			Handler:    _StakingGateway_GetChains_Handler,
		},
		{
			MethodName: "GetDelegators",
			Handler:    _StakingGateway_GetDelegators_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "staking.proto",
}
